### ISSUE TITLE
报错问题，求解答

### ISSUE THREAD

**Issue by hero258** [blinker-iot/blinker-py#56]
官方例程Hello_WiFi.py，在仅修改auth情况下，报错
Exception in thread zeroconf-Engine-1968657504:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/zeroconf-0.27.1-py3.6.egg/zeroconf/__init__.py", line 1309, in run
    reader.handle_read(socket_)
  File "/usr/local/lib/python3.6/dist-packages/zeroconf-0.27.1-py3.6.egg/zeroconf/__init__.py", line 1391, in handle_read
    self.zc.handle_query(msg, None, _MDNS_PORT)
  File "/usr/local/lib/python3.6/dist-packages/zeroconf-0.27.1-py3.6.egg/zeroconf/__init__.py", line 2678, in handle_query
    service.server,
  File "/usr/local/lib/python3.6/dist-packages/zeroconf-0.27.1-py3.6.egg/zeroconf/__init__.py", line 652, in __init__
    DNSRecord.__init__(self, name, type_, class_, ttl)
  File "/usr/local/lib/python3.6/dist-packages/zeroconf-0.27.1-py3.6.egg/zeroconf/__init__.py", line 457, in __init__
    self._expiration_time = self.get_expiration_time(100)
  File "/usr/local/lib/python3.6/dist-packages/zeroconf-0.27.1-py3.6.egg/zeroconf/__init__.py", line 484, in get_expiration_time
    return self.created + (percent * self.ttl * 10)
TypeError: unsupported operand type(s) for +: 'float' and 'str'

Traceback (most recent call last):
  File "demo1.py", line 11, in <module>
    Blinker.begin('1c6f493bb57f')
  File "/usr/local/lib/python3.6/dist-packages/Blinker-0.2.0-py3.6.egg/Blinker/Blinker.py", line 151, in begin
    bProto.conn2.start(bProto.conn1.bmqtt.deviceName)
  File "/usr/local/lib/python3.6/dist-packages/Blinker-0.2.0-py3.6.egg/BlinkerAdapters/BlinkerLinuxWS.py", line 86, in start
    mDNSinit(self.type , name)
  File "/usr/local/lib/python3.6/dist-packages/Blinker-0.2.0-py3.6.egg/BlinkerAdapters/BlinkerLinuxWS.py", line 40, in mDNSinit
    zeroconf.register_service(info)
  File "/usr/local/lib/python3.6/dist-packages/zeroconf-0.27.1-py3.6.egg/zeroconf/__init__.py", line 2385, in register_service
    self._broadcast_service(info)
  File "/usr/local/lib/python3.6/dist-packages/zeroconf-0.27.1-py3.6.egg/zeroconf/__init__.py", line 2419, in _broadcast_service
    info.server,
  File "/usr/local/lib/python3.6/dist-packages/zeroconf-0.27.1-py3.6.egg/zeroconf/__init__.py", line 652, in __init__
    DNSRecord.__init__(self, name, type_, class_, ttl)
  File "/usr/local/lib/python3.6/dist-packages/zeroconf-0.27.1-py3.6.egg/zeroconf/__init__.py", line 457, in __init__
    self._expiration_time = self.get_expiration_time(100)
  File "/usr/local/lib/python3.6/dist-packages/zeroconf-0.27.1-py3.6.egg/zeroconf/__init__.py", line 484, in get_expiration_time
    return self.created + (percent * self.ttl * 10)
TypeError: unsupported operand type(s) for +: 'float' and 'str'

**Comment by BigAlex2018** [comment]
这个问题咋解决，我也遇到了

**Comment by zsb514** [comment]
+1,同遇到

**Comment by zsb514** [comment]
把这个库降到0.26.3就好了

**Comment by hero258** [comment]
实测降低zeroconf版本号有效
步骤如下：
1.卸载最新版zeroconf
sudo pip3 uninstall zeroconf
2.下载低版本zeroconf，采用0.26.3
wget https://files.pythonhosted.org/packages/5b/c3/02e8fe31c66334db2edba41aa73eca2348e058d6def00036d02851726c50/zeroconf-0.26.3-py3-none-any.whl
3.安装
在下载zeroconf-0.26.3-py3-none-any.whl路径使用：sudo pip3 install zeroconf-0.26.3-py3-none-any.whl

**Comment by BigAlex2018** [comment]
好的，非常感谢您！------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;hero258&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月6日(星期一) 凌晨0:35
收件人:&nbsp;&quot;blinker-iot/blinker-py&quot;<blinker-py@noreply.github.com&gt;;
抄送:&nbsp;&quot;Noprint&quot;<1838978242@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [blinker-iot/blinker-py] 报错问题，求解答 (#56)

**Comment by i3water** [comment]
已更新setup/requirments
已更新语音助手支持及小爱支持
