### ISSUE TITLE
连接后报错

### ISSUE THREAD

**Issue by Skyxmao** [blinker-iot/blinker-py#60]
Hello_WIFI.py
库都是最新的。

[10:54:05 2020] subtopic:
[10:54:05 2020] pubtopic:
Traceback (most recent call last):
  File "Hello_WiFi.py", line 12, in <module>
    Blinker.begin(auth)
  File "/usr/local/lib/python3.7/dist-packages/Blinker-0.2.0-py3.7.egg/Blinker/Blinker.py", line 171, in begin
    bProto.conn1.start(auth, bProto.aliType, bProto.duerType, bProto.miType)
  File "/usr/local/lib/python3.7/dist-packages/Blinker-0.2.0-py3.7.egg/BlinkerAdapters/BlinkerMQTT.py", line 328, in start
    self.client.connect(self.bmqtt.host, self.bmqtt.port, 60)
  File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.5.1-py3.7.egg/paho/mqtt/client.py", line 940, in connect
    bind_address, bind_port, clean_start, properties)
  File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.5.1-py3.7.egg/paho/mqtt/client.py", line 1005, in connect_async
    raise ValueError('Invalid host.')
ValueError: Invalid host.
pi@raspberrypi:~/blinker-py/ex

**Comment by Skyxmao** [comment]
客户端使用阿里云mqtt就可以了
