### ISSUE TITLE
新装raspbian， python 3.7， auth 报错 invalid host

### ISSUE THREAD

**Issue by harrywenjie** [blinker-iot/blinker-py#63]
> ```bash
> pi@raspberrypi:~/blinker-py $ python --version
> Python 3.7.3
> pi@raspberrypi:~/blinker-py $ python myblinker.py
> Traceback (most recent call last):
>   File "myblinker.py", line 8, in <module>
>     Blinker.mode("BLINKER_WIFI")
>   File "/home/pi/blinker-py/Blinker/Blinker.py", line 123, in mode
>     bProto.conn2 = bProto.proto2.WebSocketServer(BLINKER_DIY_MQTT)
>   File "/home/pi/blinker-py/BlinkerAdapters/BlinkerLinuxWS.py", line 81, in __init__
>     self.server = SimpleWebSocketServer(self.name, self.port, HandleServer)
>   File "/usr/local/lib/python3.7/dist-packages/SimpleWebSocketServer-0.1.1-py3.7.egg/SimpleWebSocketServer/SimpleWebSocketServer.py", line 602, in __init__
> PermissionError: [Errno 13] Permission denied
> pi@raspberrypi:~/blinker-py $ sudo python myblinker.py
> [14:09:26 2021] url: https://iot.diandeng.tech/api/v1/user/device/diy/auth?authKey=b5d35a05b817
> [14:09:29 2021] Device Auth Data: {'detail': {'broker': 'blinker', 'deviceName': 'FD236C7EXT8MOAX8WD447G08', 'host': 'mqtts://broker.diandeng.tech', 'iotId': '9RG7376YTMrVUmVMkuxkbGhv77', 'iotToken': 'KksdZm9ATj62EPhMg4Bzqf4pZRCRHuPv', 'port': '1884', 'productKey': 'blinker', 'uuid': 'fd236c7fac6e11eb89795254'}, 'message': 1000}
> [14:09:29 2021] deviceName: FD236C7EXT8MOAX8WD447G08
> [14:09:29 2021] iotId: 9RG7376YTMrVUmVMkuxkbGhv77
> [14:09:29 2021] iotToken: KksdZm9ATj62EPhMg4Bzqf4pZRCRHuPv
> [14:09:29 2021] productKey: blinker
> [14:09:29 2021] uuid: fd236c7fac6e11eb89795254
> [14:09:29 2021] broker: blinker
> [14:09:29 2021] clientID:
> [14:09:29 2021] userName:
> [14:09:29 2021] password: 😎
> [14:09:29 2021] subtopic:
> [14:09:29 2021] pubtopic:
> Traceback (most recent call last):
>   File "myblinker.py", line 9, in <module>
>     Blinker.begin(auth)
>   File "/home/pi/blinker-py/Blinker/Blinker.py", line 171, in begin
>     bProto.conn1.start(auth, bProto.aliType, bProto.duerType, bProto.miType)
>   File "/home/pi/blinker-py/BlinkerAdapters/BlinkerMQTT.py", line 328, in start
>     self.client.connect(self.bmqtt.host, self.bmqtt.port, 60)
>   File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.5.1-py3.7.egg/paho/mqtt/client.py", line 940, in connect
>     bind_address, bind_port, clean_start, properties)
>   File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.5.1-py3.7.egg/paho/mqtt/client.py", line 1005, in connect_async
>     raise ValueError('Invalid host.')
> ValueError: Invalid host.
> pi@raspberrypi:~/blinker-py $
> ```
>
> 

python 版本3.7.3，myblinker.py 除了初始化什么也没写,  不用sudo说没权限，用sudo报错 mqtt 有个Invalid host

```python
from Blinker import *

auth = '😎'

BLINKER_DEBUG.debugAll()

Blinker.mode("BLINKER_WIFI")
Blinker.begin(auth)
```

**Comment by harrywenjie** [comment]
貌似跟别人相同的问题。
