### ISSUE TITLE
同时运行两个脚本，地址冲突问题，求解决办法

### ISSUE THREAD

**Issue by kisyu2019** [blinker-iot/blinker-py#65]
Traceback (most recent call last):
  File "wol.py", line 17, in <module>
    Blinker.mode("BLINKER_WIFI")
  File "/usr/local/lib/python3.7/site-packages/Blinker-0.2.0-py3.7.egg/Blinker/Blinker.py", line 123, in mode
    bProto.conn2 = bProto.proto2.WebSocketServer(BLINKER_DIY_MQTT)
  File "/usr/local/lib/python3.7/site-packages/Blinker-0.2.0-py3.7.egg/BlinkerAdapters/BlinkerLinuxWS.py", line 81, in __init__
    self.server = SimpleWebSocketServer(self.name, self.port, HandleServer)
  File "/usr/local/lib/python3.7/site-packages/SimpleWebSocketServer/SimpleWebSocketServer.py", line 602, in __init__
    self.serversocket.bind(hostInfo[0][4])
OSError: [Errno 98] Address already in use

**Comment by coloz** [comment]
使用最新sdk，关闭本地websocket功能即可。
```python
from blinker import Device
device = Device(auth_key, protocol: str = "mqtt", websocket: bool = True, source_check: bool = False,
                 version: str = "1.0", ali_type: str = None, duer_type: str = None, mi_type: str = None,
                 heartbeat_func=None, realtime_func=None, ready_func=None, builtin_switch_func=None)
```
websocket 开启后，会占用81端口，用于局域网中设备直接通信，如有安全性要求请关闭该功能
