### ISSUE TITLE
树莓派Hello_WiFi.py运行时报host无效

### ISSUE THREAD

**Issue by Forwardxiang** [blinker-iot/blinker-py#66]
请教一下，这个是否需要手动更改host等参数，这些参数应该怎么选择或者参考哪里？
报错信息如下：
Traceback (most recent call last):
  File "Hello_WiFi.py", line 12, in <module>
    Blinker.begin(auth)
  File "/mnt/d/Desktop/blinker-py-0.2.0/Blinker/Blinker.py", line 172, in begin
    bProto.conn1.start(auth, bProto.aliType, bProto.duerType, bProto.miType)
  File "/mnt/d/Desktop/blinker-py-0.2.0/BlinkerAdapters/BlinkerMQTT.py", line 329, in start
    self.client.connect(self.bmqtt.host, self.bmqtt.port, 60)
  File "/usr/local/lib/python3.6/dist-packages/paho_mqtt-1.5.1-py3.6.egg/paho/mqtt/client.py", line 940, in connect
    bind_address, bind_port, clean_start, properties)
  File "/usr/local/lib/python3.6/dist-packages/paho_mqtt-1.5.1-py3.6.egg/paho/mqtt/client.py", line 1005, in connect_async
    raise ValueError('Invalid host.')
ValueError: Invalid host.

**Comment by gmingtian** [comment]
我遇到的和您类似，请教下这个是怎么解决的
Traceback (most recent call last):
  File "p.py", line 21, in <module>
    Blinker.begin(auth)
  File "/usr/local/lib/python3.7/dist-packages/Blinker-0.2.0-py3.7.egg/Blinker/Blinker.py", line 171, in begin
    bProto.conn1.start(auth, bProto.aliType, bProto.duerType, bProto.miType)
  File "/usr/local/lib/python3.7/dist-packages/Blinker-0.2.0-py3.7.egg/BlinkerAdapters/BlinkerMQTT.py", line 328, in start
    self.client.connect(self.bmqtt.host, self.bmqtt.port, 60)
  File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.5.1-py3.7.egg/paho/mqtt/client.py", line 939, in connect
    bind_address, bind_port, clean_start, properties)
  File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.5.1-py3.7.egg/paho/mqtt/client.py", line 1004, in connect_async
    raise ValueError('Invalid host.')
ValueError: Invalid host.

**Comment by Forwardxiang** [comment]
代码里不要选择demo默认的mqtt,改用阿里云，具体的我忘了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月1日(星期五) 晚上11:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [blinker-iot/blinker-py] 树莓派Hello_WiFi.py运行时报host无效 (#66)





 
我遇到的和您类似，请教下这个是怎么解决的
 Traceback (most recent call last):
 File "p.py", line 21, in 
 Blinker.begin(auth)
 File "/usr/local/lib/python3.7/dist-packages/Blinker-0.2.0-py3.7.egg/Blinker/Blinker.py", line 171, in begin
 bProto.conn1.start(auth, bProto.aliType, bProto.duerType, bProto.miType)
 File "/usr/local/lib/python3.7/dist-packages/Blinker-0.2.0-py3.7.egg/BlinkerAdapters/BlinkerMQTT.py", line 328, in start
 self.client.connect(self.bmqtt.host, self.bmqtt.port, 60)
 File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.5.1-py3.7.egg/paho/mqtt/client.py", line 939, in connect
 bind_address, bind_port, clean_start, properties)
 File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.5.1-py3.7.egg/paho/mqtt/client.py", line 1004, in connect_async
 raise ValueError('Invalid host.')
 ValueError: Invalid host.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by coloz** [comment]
我们已重构py支持库，期待您的测试和反馈。
