### ISSUE TITLE
dev 3.0 运行报错 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by vjiaoziv** [blinker-iot/blinker-py#68]
输出如下
```python
pi@raspberrypi:~/Desktop $ /bin/python3 /home/pi/Desktop/blinker_control.py
Traceback (most recent call last):
  File "/home/pi/Desktop/blinker_control.py", line 1, in <module>
    from blinker import Device , ButtonWidget
  File "/home/pi/.local/lib/python3.7/site-packages/blinker/__init__.py", line 6, in <module>
    from .device import *
  File "/home/pi/.local/lib/python3.7/site-packages/blinker/device.py", line 70
    def __init__(self, /, **kw):
                       ^
SyntaxError: invalid syntax
pi@raspberrypi:~/Desktop $ 
```

**Comment by coloz** [comment]
请使用最新sdk并测试例程
