### ISSUE TITLE
dev_3.0报错接小爱同学报错 "要操作的设备好像出问题了，等一会再试"

### ISSUE THREAD

**Issue by xixioo2018** [blinker-iot/blinker-py#69]
```bash
(venv) ➜  [/home/pi/Soft/blinker-py] git:(dev_3.0) ✗ sudo python3 example/voice_assistant.py
Press Ctrl+C to exit
2022-04-11 21:13:27.355 | SUCCESS  | blinker.device:device_init:223 - Device auth successful...
2022-04-11 21:13:27.362 | INFO     | blinker.device:_cloud_heartbeat:246 - Send cloud heartbeat
2022-04-11 21:13:27.363 | INFO     | blinker.httpclient:cloud_heartbeat:128 - http cloud heartbeat
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/blinker/device.py", line 458, in init_local_service
    await zero_conf.async_register_service(info)
AttributeError: 'Zeroconf' object has no attribute 'async_register_service'
2022-04-11 21:13:27.430 | INFO     | blinker.mqttclient:_on_connect:46 - Connect to broker from mqtt
2022-04-11 21:13:27.431 | SUCCESS  | blinker.mqttclient:_on_connect:48 - Broker connected...
2022-04-11 21:13:27.432 | SUCCESS  | blinker.device:_receiver:382 - Receiver ready...
query state: state
2022-04-11 21:13:34.302 | INFO     | blinker.mqttclient:send_to_voiceassistant:115 - send mqtt message to voice assistant: {"fromDevice": "E9E2009E1MRJ4VM2VBVHB1XN", "toDevice": "ServerReceiver", "data": {"pState": "true", "mode": "day", "color": "red", "brightness": "66", "messageId": "6254297e30efdd70"}}
2022-04-11 21:13:35.375 | INFO     | blinker.mqttclient:_on_connect:46 - Connect to broker from mqtt
2022-04-11 21:13:35.376 | SUCCESS  | blinker.mqttclient:_on_connect:48 - Broker connected...

```

**Comment by werewolfst** [comment]
未复现此错误，执行并截图下 `sudo python3 -m pip show zeroconf` 得结果
